
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cars</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>
<body style="padding: 20px">
    <header>
        <h1>Creating a new car</h1>
    </header>
    <a href="list" class="btn btn-primary">Back to the list</a>
    <div style="width: 800px; margin-top: 40px;">
        <form method="post" action="create">
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" for="brand">Brand</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="brand" name="brand" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" for="model">Model</label>
                <div class="col-sm-10">
                    <input type="text" class="form-control" id="model" name="model" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" for="hp">HP</label>
                <div class="col-sm-10">
                    <input type="number" min="1" max="1500" class="form-control" id="hp" name="hp" value="80" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" for="color">Color</label>
                <div class="col-sm-10">
                    <input type="color" class="form-control" id="color" name="color" />
                </div>
            </div>
            <div class="form-group row">
                <label class="col-sm-2 col-form-label" for="price">Price in €</label>
                <div class="col-sm-10">
                    <input type="number" min="1" class="form-control" id="price" name="price" value="5000" step=".01" />
                </div>
            </div>
            <input type="submit" value="create" class="btn btn-primary" />
        </form>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>