<?php
use App\Entity\Car;
/** @var $cars Car[] */
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Cars</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>
<body style="padding: 20px">
    <header>
        <h1>List of cars</h1>
    </header>
    <a href="new" class="btn btn-primary">New</a>
    <div class="row" style="margin-top: 40px;">
        <?php foreach ($cars as $car) { ?>
            <div class="card col-sm-3">
                <div class="card-body">
                    <h5 class="card-title"><?= $car ?></h5>
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-3">
                                Color:
                            </div>
                            <div class="col-sm-9"
                                 style="background-color: <?= $car->getColor() ?>; -webkit-text-stroke: 1px black; color: #fff; font-weight: bold"
                            >
                                <?= $car->getColor() ?>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3">
                                hp:
                            </div>
                            <div class="col-sm-9" ><?= $car->getHp() ?></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3">
                                Price:
                            </div>
                            <div class="col-sm-9" ><?= $car->getPrice() ?> €</div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <a href="show?car=<?= $car->getId() ?>" class="btn btn-primary">Edit</a>
                        </div>
                        <div class="col-sm-6">
                            <form method="post" action="delete">
                                <input type="hidden" name="car" value="<?= $car->getId() ?>" />
                                <input type="submit" class="btn btn-secondary" value="remove" />
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>